repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-csslint
    rev: v1.0.5
    hooks:
      - id: csslint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.4.1"
    hooks:
      - id: eslint
