name: Build, lint, and Deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install dependencies
        run: |
          yarn install
      - name: ESLint
        run: yarn lint
      - name: Typechecking
        run: yarn typecheck
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Build
        run: |
          yarn install
          yarn build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
